dels_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import CustomPasswordChangeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/password/change/', CustomPasswordChangeView.as_view()),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('groups/', include('groups.urls')),
    path('subjects/', include('subjects.urls')),
    path('calendar/', include('calendars.urls')),

    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

subjects/urls.py
from django.urls import path

from subjects.views import *

urlpatterns = [
    path('<int:pk>/teacher', TeacherSubjectView.as_view(), name='teacher_subject'),
    path('<int:pk>/teacher/post_create', TeacherPostCreationView.as_view(), name='post_create_teacher'),
    path('<int:pk>/teacher/task_create', TeacherTaskCreationView.as_view(), name='task_create_teacher'),
    path('<int:pk>/teacher/post_detail/<int:id>', SubjectTeacherPostDetailView.as_view(), name='post_detail_subject'),
    path('<int:pk>/post_detail/<int:id>', SubjectStudentPostDetailView.as_view(), name='post_detail_subject'),
    path('<int:pk>/teacher/task_detail/<uuid:id>', TeacherTaskDetailView.as_view(), name='teacher_task_detail_subject'),
    path('<int:pk>/task_detail/<uuid:id>', StudentTaskDetailView.as_view(), name='student_task_detail_subject'),
    path('<int:pk>/task_done_detail/<uuid:id>', StudentTaskDoneDetailsView.as_view(), name='student_task_done_detail_subject'),
    path('<int:pk>/task_return/<uuid:id>', StudentTaskDoneCreateView.as_view(), name='student_task_done_subject'),
    path('<int:pk>/task_detail/<uuid:id>', TeacherTaskDetailView.as_view(), name='task_detail_subject'),
    path('<int:pk>/teacher/tasks_done/<uuid:id>', TasksDoneListView.as_view(), name='task_done_list'),
    path('teacher/task_done/<uuid:id>', TaskDoneTeacherEditView.as_view(), name='task_done_teacher_edit'),
    path('<int:pk>/teacher/resource_create', TeacherResourceCreateView.as_view(), name='resource_create'),
    path('<int:pk>/teacher/resource_delete/<uuid:id>', TeacherResourceDeleteView.as_view(), name='resource_delete'),
    path('teacher/create_subject', TeacherCreateSubjectView.as_view(), name='subject_create_teacher'),
    path('<int:pk>/teacher/add_students', TeacherAddStudentsView.as_view(), name='teacher_add_students'),
    path('<int:pk>', StudentSubjectView.as_view(), name='student_subject'),
    path('', SubjectsListView.as_view(), name='subjects_list'),
]

subjects/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


def dir_name(instance, filename):
    idd = (str(instance.id))
    return f"{idd}/{filename}"


class Teacher(models.Model):
    teacher = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.teacher.username


class Subject(models.Model):
    id = models.AutoField(primary_key=True)
    subject_name = models.CharField(max_length=255)
    teachers = models.ManyToManyField(Teacher)
    students = models.ManyToManyField(get_user_model())

    def __str__(self):
        return self.subject_name

    def get_absolute_url(self):
        return reverse('teacher_subject', args=[str(self.id)])


class PostInSubject(models.Model):
    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    body = models.TextField()
    pub_date = models.DateTimeField('date_published', auto_now_add=True)

    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse('teacher_subject', args=[str(self.subject_id)])


class CommentInSubject(models.Model):
    post = models.ForeignKey(
        PostInSubject,
        on_delete=models.CASCADE,
        related_name='comments',
    )

    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    body = models.TextField(max_length=4000)
    pub_date = models.DateTimeField('date_published', auto_now_add=True)

    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse('post_detail_subject', args=[
            str(self.post.subject_id),
            str(self.post_id)
        ])


class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
    )
    pub_date = models.DateTimeField('date_published', auto_now_add=True)
    deadline = models.DateField('date to end')
    body = models.TextField()

    file = models.FileField(upload_to=f"tasks/to_do/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse('teacher_subject', args=[str(self.subject_id)])


class CommentTask(models.Model):
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )

    body = models.TextField(max_length=4000)
    pub_date = models.DateTimeField('date_published', auto_now_add=True)

    def __str__(self):
        return self.body

    def get_absolute_url(self):
        return reverse('task_detail_subject', args=[
            str(self.task.subject_id),
            str(self.task_id)
        ])


class TaskDone(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    task = models.ForeignKey(
        Task,
        on_delete=models.CASCADE,
        related_name='tasks_done',
    )
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    pub_date = models.DateTimeField('date_published', auto_now_add=True)
    message = models.TextField(max_length=4000, null=True, blank=True)
    feedback = models.TextField(max_length=4000, null=True, blank=True)
    grade = models.CharField(max_length=100, null=True, blank=True)
    file = models.FileField(upload_to=f"done_tasks/", null=True, blank=True)

    NotDone = 1
    Done = 2
    ToEdit = 3
    STATUS = (
        (NotDone, _('Not done')),
        (Done, _('Done')),
        (ToEdit, _('To edit')),
    )
    status = models.SmallIntegerField(
        choices=STATUS,
        default=1,
    )

    def get_absolute_url(self):
        return reverse('student_subject', args=[
            str(Task.objects.get(id=self.task_id).subject_id)
        ])


class Resource(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4(), editable=False, unique=True)
    subject = models.ForeignKey(
        Subject,
        on_delete=models.CASCADE,
        related_name='resources',
    )
    name = models.CharField(max_length=255)
    body = models.TextField(max_length=4000)
    pub_date = models.DateTimeField('date_published', auto_now_add=True)
    file = models.FileField(upload_to=f"resources/", null=True, blank=True)

    def get_absolute_url(self):
        return reverse('teacher_subject', args=[
            str(self.subject_id)
        ])


class TeacherToSubject(models.Model):
    teacher = models.ForeignKey('Teacher', related_name='subject_teachers', on_delete=models.CASCADE)
    subject = models.ForeignKey('Subject', related_name='subject_teachers', on_delete=models.CASCADE)

subjects/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, FormView, TemplateView

from calendars.models import add_event
from users.models import StudentGroup
from .forms import TaskCreationForm, ResourceCreationForm, StudentGroupAddForm
from .models import PostInSubject, Task, Resource, Subject, CommentInSubject, CommentTask, TaskDone, Teacher


class TeacherSubjectView(LoginRequiredMixin, ListView):
    template_name = 'subjects/teacher_subject.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))
        context = super().get_context_data(**kwargs)
        if get_object_or_404(subject.teachers, teacher=self.request.user):
            context['tasks'] = Task.objects.filter(subject_id=int(self.kwargs['pk'])).order_by('-pub_date')
            context['resources'] = Resource.objects.filter(subject_id=int(self.kwargs['pk'])).order_by('-pub_date')
            context['subject'] = subject
            return context
        return context

    def get_queryset(self):
        return PostInSubject.objects.filter(subject_id=int(self.kwargs['pk'])).order_by('-pub_date')


class TeacherPostCreationView(LoginRequiredMixin, CreateView):
    model = PostInSubject
    template_name = 'subjects/teacher_posts_creation.html'
    fields = [
        'body',
    ]

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.subject = Subject.objects.get(id=int(self.kwargs['pk']))
        return super().form_valid(form)


class SubjectTeacherPostDetailView(LoginRequiredMixin, CreateView):
    model = CommentInSubject
    template_name = 'subjects/subject_post_detail.html'
    fields = [
        'body',
    ]

    def get(self, request, *args, **kwargs):
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))

        if get_object_or_404(subject.teachers, teacher=self.request.user) or \
                get_object_or_404(subject.students, id=self.request.user.id):
            return super().get(request, *args, **kwargs)

        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        post = get_object_or_404(PostInSubject, pk=int(self.kwargs['id']))
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))

        if get_object_or_404(subject.teachers, teacher=self.request.user) or \
                get_object_or_404(subject.students, id=self.request.user.id):
            context = super().get_context_data(**kwargs)
            context['post'] = post
            context['comments'] = self.model.objects.filter(post_id=int(self.kwargs['id'])).order_by('-pub_date')
            return context

        return HttpResponseForbidden()

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = PostInSubject.objects.get(id=int(self.kwargs['id']))
        return super().form_valid(form)


class TeacherTaskCreationView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskCreationForm
    template_name = 'subjects/teacher_tasks_creation.html'

    def form_valid(self, form):
        form.instance.subject = Subject.objects.get(id=int(self.kwargs['pk']))
        add_event(
            subject_id=int(self.kwargs['pk']),
            date=form.instance.deadline,
            name=f'Task to do in {form.instance.subject.subject_name}',
            body=form.instance.body
        )
        return super().form_valid(form)


class TeacherTaskDetailView(LoginRequiredMixin, CreateView):
    model = CommentTask
    template_name = 'subjects/teacher_task_detail.html'
    fields = [
        'body',
    ]

    def get(self, request, *args, **kwargs):
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))

        if get_object_or_404(subject.teachers, teacher=self.request.user) or \
                get_object_or_404(subject.students, user=self.request.user):
            return super().get(request, *args, **kwargs)

        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        task = get_object_or_404(Task, pk=self.kwargs['id'])
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))

        if get_object_or_404(subject.teachers, teacher=self.request.user) or \
                get_object_or_404(subject.students, user=self.request.user):
            context = super().get_context_data(**kwargs)
            context['task'] = task
            context['comments'] = self.model.objects.filter(task_id=self.kwargs['id']).order_by('-pub_date')
            return context

        return HttpResponseForbidden()

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.task = Task.objects.get(id=self.kwargs['id'])
        return super().form_valid(form)


class TeacherResourceCreateView(LoginRequiredMixin, CreateView):
    model = Resource
    template_name = 'subjects/teacher_resource_creation.html'
    form_class = ResourceCreationForm

    def form_valid(self, form):
        form.instance.subject = Subject.objects.get(id=int(self.kwargs['pk']))
        return super().form_valid(form)


class TeacherResourceDeleteView(LoginRequiredMixin, DeleteView):
    model = Resource
    template_name = 'subjects/teacher_resource_delete.html'
    pk_url_kwarg = 'id'

    def get_success_url(self):
        subject = self.object.subject
        return reverse_lazy('teacher_subject', args=[str(subject.id)])


class TasksDoneListView(LoginRequiredMixin, ListView):
    model = TaskDone
    template_name = 'subjects/teacher_tasks_done.html'
    user = get_user_model()
    context_object_name = 'tasks_done'

    def get_queryset(self):
        return TaskDone.objects.filter(task_id=self.kwargs['id']).order_by('-pub_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = Subject.objects.get(pk=int(self.kwargs['pk']))
        context['students'] = subject.students.all()
        return context


class TaskDoneTeacherEditView(LoginRequiredMixin, UpdateView):
    model = TaskDone
    template_name = 'subjects/teacher_task_done_edit.html'
    fields = [
        'grade',
        'feedback',
        'status'
    ]
    context_object_name = 'done'
    pk_url_kwarg = 'id'

    def get_success_url(self):
        done = TaskDone.objects.get(id=self.kwargs['id'])
        task = Task.objects.get(id=done.task_id)
        subject = Subject.objects.get(id=task.subject_id)
        return reverse_lazy('task_done_list', args=[str(subject.id), task.id])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task_done'] = self.model.objects.get(id=self.kwargs['id'])
        return context


class TeacherCreateSubjectView(LoginRequiredMixin, CreateView):
    model = Subject
    fields = ['subject_name']
    template_name = 'subjects/teacher_subject_create.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        form.instance.teachers.add(Teacher.objects.get(teacher_id=self.request.user.id))
        return super().form_valid(form)


class TeacherAddStudentsView(LoginRequiredMixin, FormView):
    form_class = StudentGroupAddForm
    template_name = 'subjects/teacher_add_students.html'

    def get_success_url(self):
        subject = Subject.objects.get(pk=int(self.kwargs['pk']))
        return reverse_lazy('teacher_subject', args=[str(subject.id)])

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if form.is_valid() and StudentGroup.objects.filter(name=form.data['group']).exists():
            group = StudentGroup.objects.get(name=form.data['group'])
            user = get_user_model()
            subject = Subject.objects.get(pk=int(self.kwargs['pk']))
            for student in user.objects.filter(student_group_id=group.id):
                subject.students.add(student.id)
                subject.save()

            return HttpResponseRedirect(reverse('teacher_subject', args=[str(subject.id)]))

        return render(request, self.template_name, {'form': form, 'error_message': "wrong group"})


class StudentSubjectView(LoginRequiredMixin, ListView):
    template_name = 'subjects/student_subject.html'
    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))
        context = super().get_context_data(**kwargs)
        if get_object_or_404(subject.students, id=self.request.user.id):
            context['tasks'] = Task.objects.filter(subject_id=int(self.kwargs['pk'])).order_by('-pub_date')
            context['resources'] = Resource.objects.filter(subject_id=int(self.kwargs['pk'])).order_by('-pub_date')
            context['subject'] = subject
            return context
        return context

    def get_queryset(self):
        return PostInSubject.objects.filter(subject_id=int(self.kwargs['pk'])).order_by('-pub_date')


class SubjectStudentPostDetailView(LoginRequiredMixin, CreateView):
    model = CommentInSubject
    template_name = 'subjects/subject_post_detail.html'
    fields = [
        'body',
    ]

    def get(self, request, *args, **kwargs):
        subject = get_object_or_404(Subject, pk=int(self.kwargs['pk']))

        if get_object_or_404(subject.students, id=self.request.user.id):
            return super().get(request, *args, **kwargs)

        return HttpResponseForbidden()

    def get_context_data(self, **kwargs):
        post = get_object_or_404(PostInSubject, pk=int(self.kwargs['id']))

templates/subjects/student_resources.html
<div class="tab-pane fade" id="v-pills-resources" role="tabpanel" aria-labelledby="v-pills-resources-tab">

    {% for resource in resources %}
        <div class="card mt-3 mx-auto shadow-sm">
            <div class="card-body pb-1">
                <p>{{ resource.body }}</p>
                <hr>
                {% if resource.file %}
                    <a href="{{ resource.file.url }}">download task files</a>
                {% endif %}
            </div>
        </div>
    {% endfor %}

</div>

templates/subjects/student_subject.html
{% extends '_base.html' %}

{% block title %}{{ subject.name }}{% endblock %}

{% block content %}
    <div class="row mt-2">
        <div class="col-3 mt-3">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link active" id="v-pills-posts-tab" data-toggle="pill" href="#v-pills-posts"
                   role="tab" aria-controls="v-pills-posts" aria-selected="true">Posts</a>
                <a class="nav-link" id="v-pills-tasks-tab" data-toggle="pill" href="#v-pills-tasks" role="tab"
                   aria-controls="v-pills-tasks" aria-selected="false">Tasks</a>
                <a class="nav-link" id="v-pills-resources-tab" data-toggle="pill" href="#v-pills-resources" role="tab"
                   aria-controls="v-pills-resources" aria-selected="false">Resources</a>
                <a class="nav-link" id="v-pills-video-tab" data-toggle="pill" href="#v-pills-video" role="tab"
                   aria-controls="v-pills-video" aria-selected="false">Video</a>
            </div>
        </div>

        <div class="col-9">
            <div class="card mt-3 mx-auto shadow-sm bg-light">
                <div class="card-body">
                    <a class="btn btn-primary ml-1" type="button"
                    href="{% url 'post_create_teacher' subject.pk %}">Publish a post</a>
                </div>
            </div>

            <div class="tab-content" id="v-pills-tabContent">

                {% include 'subjects/subject_posts.html' %}
                {% include 'subjects/student_tasks.html' %}
                {% include 'subjects/student_resources.html' %}
                {% comment %}
                {% include teacher_video.html %}
                {% endcomment %}
            </div>
        </div>

    </div>
{% endblock %}

templates/subjects/student_task_detail.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Task details{% endblock %}

{% block content %}
    <div class="card mt-3 mx-auto shadow-sm bg-light" style="width: 60%">
        <div class="card-body">
            {% if not isDone %}
                <a class="btn btn-primary ml-1" type="button"
               href="{% url 'student_task_done_subject' task.subject.pk task.id %}">Return Task</a>
            {% endif %}

            <a class="btn btn-primary ml-1" type="button"
               href="{% url 'student_task_done_detail_subject' task.subject.pk task.id %}">Returned Task</a>
        </div>
    </div>
    <div class="card mt-3 mx-auto shadow-sm" style="width: 60%">
        <div class="card-body pb-4">
            <p class="mb-5">
                <span class="font-weight-lighter text-muted float-right">
                    {{ task.pub_date }}
                </span>
            </p>
            <hr>
            <p>{{ task.body }}</p>
            <hr>
            {% if task.file %}
                <a href="{{ task.file.url }}">download task files</a>
            {% endif %}
        </div>
    </div>

    <form method="post" class="mt-4 mx-auto" style="width: 60%">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Publish a comment</h5>
                <textarea placeholder="You can write a comment right there" class="form-control"
                          type="text" id="body" name="body" required></textarea>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary float-right" type="submit">Comment</button>
            </div>
        </div>
    </form>

    {% for comment in comments %}
        <div class="card mt-3 mx-auto shadow-sm" style="width: 60%">
        <div class="card-body pb-1">
            <p>
                <span class="font-weight-bold">{{ comment.author }}: </span>
                <span class="text-mutex">
                    {{ comment.body }}</span>
            </p>
        </div>
    </div>
    {% endfor %}

{% endblock %}

templates/subjects/student_task_done_creation.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Return Task{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Done</button>
    </form>
{% endblock %}

templates/subjects/student_task_done_details.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Returned Task{% endblock %}

{% block content %}
    <div class="card mt-3 mx-auto shadow-sm" style="width: 60%">
        <div class="card-body pb-4">
            <p class="mb-5">
                {% if task_done.grade != null %}
                    <span class="card-title font-weight-bold">{{ task_done.grade }}</span>
                {% endif %}
                <span class="font-weight-lighter text-muted float-right">
                    {{ task_done.pub_date }}
                </span>
            </p>
            <hr>
            <p>{{ task_done.message }}</p>
            <hr>
            {% if task_done.feedback != null %}
            <p>{{ task_done.feedback }}</p>
            {% endif %}
            {% if task_done.file %}
                <a href="{{ task_done.file.url }}">download task files</a>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/subjects/student_tasks.html
<div class="tab-pane fade" id="v-pills-tasks" role="tabpanel" aria-labelledby="v-pills-tasks-tab">

    {% for task in tasks %}
        <div class="card mt-3 mx-auto shadow-sm">
            <div class="card-body pb-1">
                <p>{{ task.body }}</p>
                <hr>
                {% if task.file %}
                    <a href="{{ task.file.url }}">download task files</a>
                {% endif %}
            </div>

            <div class="card-footer mt-3">
                <a href="{% url 'task_detail_subject' subject.pk task.id %}" class="btn btn-primary" type="button">Details</a>
            </div>
        </div>
    {% endfor %}

</div>

templates/subjects/subject_posts.html
<div class="tab-pane fade show active" id="v-pills-posts" role="tabpanel" aria-labelledby="v-pills-posts-tab">



    {% for post in posts %}
        <div class="card mt-3 mx-auto shadow-sm">
                <div class="card-body pb-1">
                    <p>
                        <span class="card-title font-weight-bold">{{ post.author }}</span>
                        <a href="{% url 'post_detail_subject' subject.pk post.id %}"
                           class="text-decoration-none font-weight-lighter text-muted float-right">
                            {{ post.pub_date }}</a>
                    </p>
                    <hr>
                    <p>{{ post.body }}</p>
                    <hr>
                    <p>
                        <span>
                            <a href="{% url 'post_detail_subject' subject.pk post.id %}"
                               class="text-decoration-none">Comment</a>
                        </span>
                        <span class="float-right font-weight-lighter text-muted">
                            Comments: {{ post.comments.all.count }}</span>
                    </p>
                </div>
            </div>
    {% endfor %}
</div>

templates/subjects/subjects_list.html
{% extends '_base.html' %}

{% block title %}Subjects{% endblock %}

{% block content %}
    <div class="card-deck">
        {% if isTeacher %}
            <div class="card m-3 bg-light" style="min-width:18rem; max-width:30.5%">
            <div class="card-body">
                <h5 class="card-title">Create new subject</h5>
                <a class="btn btn-primary" href="{% url 'subject_create_teacher' %}">Create</a>
            </div>
        </div>
        {% endif %}

        {% for subject in subject_list %}
            <div class="card m-3" style="min-width:18rem; max-width:30.5%">
                <div class="card-body">
                    <h5 class="card-title">{{ subject.subject_name }}</h5>
                    {% if isTeacher %}
                        <a class="btn btn-primary" href="{% url 'teacher_subject' subject.id %}">Enter</a>
                    {% else %}
                        <a class="btn btn-primary" href="{% url 'student_subject' subject.id %}">Enter</a>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/subjects/task_detail.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Task details{% endblock %}

{% block content %}
    <div class="card mt-3 mx-auto shadow-sm" style="width: 60%">
        <div class="card-body pb-4">
            <p class="mb-5">
                <span class="font-weight-lighter text-muted float-right">
                    {{ task.pub_date }}
                </span>
            </p>
            <hr>
            <p>{{ task.body }}</p>
            <hr>
            {% if task.file %}
                <a href="{{ task.file.url }}">download task files</a>
            {% endif %}
        </div>
    </div>

    <form method="post" class="mt-4 mx-auto" style="width: 60%">
        {% csrf_token %}
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Publish a comment</h5>
                <textarea placeholder="You can write a comment right there" class="form-control"
                          type="text" id="body" name="body" required></textarea>
            </div>
            <div class="card-footer">
                <button class="btn btn-primary float-right" type="submit">Comment</button>
            </div>
        </div>
    </form>

    {% for comment in comments %}
        <div class="card mt-3 mx-auto shadow-sm" style="width: 60%">
        <div class="card-body pb-1">
            <p>
                <span class="font-weight-bold">{{ comment.author }}: </span>
                <span class="text-mutex">
                    {{ comment.body }}</span>
            </p>
        </div>
    </div>
    {% endfor %}

{% endblock %}

templates/subjects/teacher_add_students.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Add students{% endblock %}

{% block content %}
    <span>{{ error_message }}</span>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Add</button>
    </form>
{% endblock %}

templates/subjects/teacher_resources.html
<div class="tab-pane fade" id="v-pills-resources" role="tabpanel" aria-labelledby="v-pills-resources-tab">

    {% for resource in resources %}
        <div class="card mt-3 mx-auto shadow-sm">
            <div class="card-body pb-1">
                <p>{{ resource.body }}</p>
                <hr>
                {% if resource.file %}
                    <a href="{{ resource.file.url }}">download task files</a>
                {% endif %}
            </div>
        <div class="card-footer">
            <a href="{% url 'resource_delete' subject.pk resource.id %}">Delete</a>
        </div>
        </div>
    {% endfor %}

</div>

templates/subjects/teacher_subject_create.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}create subject{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">Create</button>
    </form>
{% endblock %}

templates/subjects/teacher_tasks.html
<div class="tab-pane fade" id="v-pills-tasks" role="tabpanel" aria-labelledby="v-pills-tasks-tab">

    {% for task in tasks %}
        <div class="card mt-3 mx-auto shadow-sm">
            <div class="card-body pb-1">
                <p>{{ task.body }}</p>
                <hr>
                {% if task.file %}
                    <a href="{{ task.file.url }}">download task files</a>
                {% endif %}

            </div>
        <div class="card-footer mt-3">
            <a href="{% url 'task_detail_subject' subject.pk task.id %}" class="btn btn-primary" type="button">Comments</a>
            <a href="{% url 'task_done_list' subject.pk task.id %}" class="btn btn-success" type="button">Returned tasks</a>
        </div>
        </div>
    {% endfor %}

</div>

templates/subjects/teacher_tasks_creation.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Task creation{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Publish</button>
    </form>
{% endblock %}