dels_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from users.views import CustomPasswordChangeView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/password/change/', CustomPasswordChangeView.as_view()),
    path('accounts/', include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path('groups/', include('groups.urls')),
    path('subjects/', include('subjects.urls')),
    path('calendar/', include('calendars.urls')),

    path('', include('pages.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import HomePageView


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


class StudentGroup(models.Model):
    name = models.CharField(
        unique=True,
        null=False,
        blank=False,
        max_length=255
    )

    def __str__(self):
        return self.name


class CustomUser(AbstractUser):
    index_number = models.CharField(
        max_length=7,
        unique=True,
        null=True,
        blank=True
    )
    student_group = models.ForeignKey(
        StudentGroup,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )

    A, B, C, D, E = 1, 2, 3, 4, 5
    SUB_GROUP = (
        (A, _('A')),
        (B, _('B')),
        (C, _('C')),
        (D, _('D')),
        (E, _('E')),
    )
    sub_group = models.PositiveSmallIntegerField(
        choices=SUB_GROUP,
        default=1,
        null=True,
        blank=True
    )
    REQUIRED_FIELDS = [
        'first_name',
        'last_name',
        'email',
    ]
    first_name = models.CharField(max_length=255, blank=False, null=True)
    last_name = models.CharField(max_length=255, blank=False, null=True)

    def get_absolute_url(self):
        return reverse('user_profile')

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Diploma E-learning System{% endblock title %}</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container">
            <a href="{% url 'home' %}" class="navbar-brand">
            D.e.L.S.
            </a>

            <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'student_group' %}">Group</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'subjects_list' %}">Subjects</a>
                    </li>
                </ul>

                {% if user.is_authenticated %}
                    {{ user.email }}

                    <div class="dropdown">
                        <a class="btn btn-secondary dropdown-toggle ml-2" href="#" role="button" id="dropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'user_profile' %}">Profile</a>
                            <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
                        </div>
                    </div>
                {% else %}
                    <a class="btn btn-outline-secondary" href="{% url 'account_login' %}">Log In</a>
                    <a class="btn btn-outline-primary ml-2" href="{% url 'account_signup' %}">Sign Up</a>
                {% endif %} 
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
            integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
            crossorigin="anonymous"></script>
</body>
</html>

templates/email_change.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Change email{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">change</button>
    </form>
{% endblock %}

templates/home.html
{% extends '_base.html' %}

{% block title %}
Home Page
{% endblock %}

{% block content %}
    <h1>Homepage</h1>
{% endblock %}

templates/signup.html
{% extends '_base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class='btn btn-success' type="submit">Sign Up</button>
    </form>
{% endblock %}

templates/user_profile.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}

{% block title %}Profile{% endblock %}
{% block content %}
<div class="row">
    <div class="col-3">
        <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
            <a class="nav-link active" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile"
               role="tab" aria-controls="v-pills-profile" aria-selected="true">Profile</a>
            <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab"
               aria-controls="v-pills-settings" aria-selected="false">Settings</a>
        </div>
    </div>

    <div class="col-9">
        <div class="tab-content" id="v-pills-tabContent">
            <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel"
                 aria-labelledby="v-pills-profile-tab">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <h3 class="mb-4">Personal Data</h3>
                        <p><b>First name:</b> {{ object.first_name }}</p>
                        <p><b>Last name:</b> {{ object.last_name }}</p>
                    </li>
                    <li class="list-group-item">
                        <h3 class="mb-4">Account Data</h3>
                        <p><b>User name:</b> {{ object.username }}</p>
                        <p><b>Email address:</b> {{ object.email }}</p>
                    </li>
                    <li class="list-group-item">
                        <h3 class="mb-4">Student Data</h3>
                        <p><b>Index number: </b>{{ object.index_number }}</p>
                        <p><b>Student group: </b>{{ object.student_group }}</p>
                        <p><b>Sub group:</b> {{ object.get_sub_group_display }}</p>
                    </li>
                </ul>
            </div>
            <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <div class="row ml-5">
                            <div class="col-4">
                                <h3>Account info</h3>
                                <a class="mb-3 btn btn-outline-info btn-block" href="{% url 'account_change_password' %}">
                                    Change password</a>
                                <a class="btn btn-outline-info btn-block" href="{% url 'email_change' %}">Change email</a>
                            </div>
                            <div class="col-4">
                                <h3>Student info</h3>
                                <form method="post">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit" class="btn btn-success">Save</button>
                                </form>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>


{% endblock %}